export const metadata = { title: 'Privacy | idify your X' };

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-x-bg text-x-text px-6 py-12">
      <article className="max-w-2xl mx-auto space-y-6 text-[16px] leading-7">
        <h1 className="text-3xl font-bold">Privacy notice</h1>
        <p>Last updated: September 22, 2026.</p>
        <p>When you submit an X username, idify your X retrieves publicly available profile information and recent posts from SocialData, then sends the selected information to OpenAI to generate an analysis. We use Cloudflare Turnstile to protect the service from automated abuse.</p>
        <p>We do not create user accounts or intentionally store analyses in this application. Our hosting, analytics, security, and service providers may process limited technical data such as IP address, browser details, and request metadata under their own terms and retention practices.</p>
        <p>Do not submit information that you are not permitted to share. The analysis is generated by AI and may be inaccurate. To request privacy help, contact the operator at the contact method published on the service.</p>
      </article>
    </main>
  );
}
